"""rename address

Revision ID: 4f273dc07cac
Revises: 556a0a8fbd98
Create Date: 2024-10-11 04:30:02.069257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f273dc07cac'
down_revision = '556a0a8fbd98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    # op.drop_column('departments', 'address')
    # with op.batch_alter_table('departments', schema= None) as batch_op:
    #     batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
    #     batch_op.drop_column('address')
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    # op.drop_column('departments', 'location')
    # with op.batch_alter_table('departments', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
    #     batch_op.drop_column('location')
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
