"""rename department

Revision ID: 556a0a8fbd98
Revises: 6c2387b1957c
Create Date: 2024-10-11 04:23:11.477304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556a0a8fbd98'
down_revision = '6c2387b1957c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('deparments',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('address', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('deparment')
    op.rename_table('deparment', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('deparment',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('name', sa.VARCHAR(), nullable=False),
    # sa.Column('address', sa.VARCHAR(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('deparments')
    op.rename_table('departments','deparment')
    # ### end Alembic commands ###
